version: '3.7'
services: 

  mongodb:  
    image: mongo
    restart: always
    container_name: polynote-mongodb
    volumes:
      - ./mnt/data/polynote:/data/db
    networks:
      - backend

  # backend:
  #   depends_on:
  #   - mongodb
  #   container_name: polynote-backend
  #   build: ./backend
  #   ports: 
  #   - "3000:3000"
  #   networks:
  #   - backend
  #   extra_hosts:
  #   - "host.docker.internal:host-gateway"
  #   command: npm run start:dev
    # environment:
    #   - MONGO_URI=mongodb://mongodb:27017/mydatabase  
  
  # frontend:
  #   container_name: polynote-frontend
  #   build: ./frontend
  #   ports: 
  #   - "80:80"
  #   - "443:443"

networks:
  backend:
    driver: bridge

  