#
name: polynotes-backend
namespace: thomas

replicaCount: 1

image:
  repository: thomasmauran/polynotes-backend
  pullPolicy: Always
  tag: latest

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi


env:
  name: "backend-configmap"
  databaseUrl: "mongodb://172.20.0.2:27017/polynotes"
  mongoUser: "admin"
  mongoHost: "localhost"
  mongoPort: "27017"

  appBaseUrl: "api.polynotes.cluster-2022-6.dopolytech.fr"

  mailerHost: "smtp.umontpellier.fr"
  mailerPort: "587"
  mailerSecure: "true"

  frontendOrigin: "polynotes.cluster-2022-6.dopolytech.fr"

secret:
- name: "JWT_KEY"
  secretName: "polynotes-thomas-pwd"
  key: "jwt_key"

- name: "MAILER_PASSWORD"
  secretName: "polynotes-thomas-pwd"
  key: "mailer-password"

- name: "MONGO_URL"
  secretName: "polynotes-thomas-pwd"
  key: "mongo-url"
