#
name: polynotes-backend
namespace: thomas

replicaCount: 1

image:
  repository: thomasmauran/polynotes-backend
  pullPolicy: Always
  tag: 836d5b2

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

env:
- name: MAILER_HOST
  value: "smtp.umontpellier.fr"
- name: MAILER_PORT
  value: "587"
- name: MAILER_USER
  value: "thomas.mauran@etu.umontpellier.fr"
- name: APP_BASE_URL
  value: "polynotes.cluster-2022-6.dopolytech.fr/api"
- name: FRONTEND_ORIGIN
  value: "polynotes.cluster-2022-6.dopolytech.fr"

- name: JWT_KEY
  valueFrom:
    secretKeyRef:
      name: "polynotes-thomas-pwd"
      key: "jwt_key"
- name: MAILER_PASSWORD
  valueFrom:
    secretKeyRef:
      name: "polynotes-thomas-pwd"
      key: "mailer-password"
- name: MONGO_URL
  valueFrom:
    secretKeyRef:
      name: "polynotes-thomas-pwd"
      key: "mongo-url"

