#
name: polynotes-frontend
namespace: thomas

replicaCount: 1

image:
  repository: thomasmauran/polynotes-frontend
  pullPolicy: Always
  tag: latest

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

env:
- name: VITE_APP_BASE_URL
  value: "https://polynotes.cluster-2022-6.dopolytech.fr/api"
- name: VITE_APP_TENOR_API_KEY
  valueFrom:
    secretKeyRef:
      name: "polynotes-thomas-pwd"
      key: "tenor-key"

