apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.env.name }}-env
  namespace: {{ .Values.namespace }}
data:
  DATABASE_URL: {{ .Values.env.databaseUrl }}


  APP_BASE_URL: {{ .Values.env.appBaseUrl }}

  MAILER_HOST: {{ .Values.env.mailerHost }}
  MAILER_PORT: {{ .Values.env.mailerPort }}
  MAILER_SECURE: {{ .Values.env.mailerSecure }}
  MAILER_USER: {{ .Values.env.mailerUser }}

  FRONTEND_ORIGIN: {{ .Values.env.frontendOrigin }}
  
  # Add more environment variables as needed
