namespace: thomas

ingress:
  enabled: true
  name: "polynotes"
  tls: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
routes:
# External access to the service in a cluster
- serviceName: "polynotes-frontend"
  path: "/"
  host: "polynotes.cluster-2022-6.dopolytech.fr"

- serviceName: "polynotes-backend"
  path: "/"
  host: "api.polynotes.cluster-2022-6.dopolytech.fr"

mongodb:
  auth:
    usernames:
    - "admin"
    databases:
    - "polynotes"
    existingSecret: "polynotes-thomas-pwd"

# status:
#   loadBalancer:
#     ingress: {{ toYaml .Values.ingress | nindent 4 }}
